version: '3'

services:
  app:
    build: .
    entrypoint: ./start.sh
    container_name: marketeasystore-api
    restart: always
    command: "npm start"
    working_dir: /app
    ports:
      - 3002:3002
      - 9229:9229
    volumes:
      - ./:/app
    network_mode: host
    depends_on: 
      - db

  db:
    image: postgres
    container_name: marketeasystore-db
    restart: always
    ports:
      - 5432:5432
    tty: true
    environment:
      - POSTGRES_USER=marketeasystore
      - POSTGRES_PASSWORD=marketeasystore
      - POSTGRES_DB=marketeasystore

    volumes:
      - pgdata:/data/postgres
    network_mode: host

    
volumes:
  pgdata:

  

